import { config } from './config.mjs';

export function parseJson(text) {
  const cleaned = String(text || '')
    .replace(/^\s*```(?:json)?/i, '')
    .replace(/```\s*$/, '')
    .trim();
  return JSON.parse(cleaned);
}

function normalizeMinecraftName(name) {
  return String(name || '')
    .trim()
    .replace(/^minecraft:/i, '')
    .replace(/^minecraft_/i, '');
}

function normalizeTargets(targets) {
  if (!targets || typeof targets !== 'object' || Array.isArray(targets)) return {};
  const out = {};
  for (const [rawName, value] of Object.entries(targets)) {
    const name = normalizeMinecraftName(rawName);
    if (!name) continue;
    out[name] = value;
  }
  return out;
}

export function normalizePlan(plan, fallbackId=null) {
  return {
    ...(fallbackId != null ? {id: String(plan?.id || fallbackId)} : {}),
    objective: String(plan?.objective || 'Observe the world and make safe progress.'),
    targets: normalizeTargets(plan?.targets),
    waypoint: plan?.waypoint && Number.isFinite(Number(plan.waypoint.x))
      ? {
          x: Number(plan.waypoint.x),
          y: Number(plan.waypoint.y),
          z: Number(plan.waypoint.z)
        }
      : null,
    desiredBlocks: Array.isArray(plan?.desiredBlocks)
      ? [...new Set(plan.desiredBlocks.map(normalizeMinecraftName).filter(Boolean))].slice(0, 12)
      : [],
    notes: String(plan?.notes || '')
  };
}

const sharedRules = `
Rules:
- Use only information present in the supplied state.
- Keep the objective achievable with the CURRENT agent capabilities listed below.
- Prefer small, immediate milestones.
- Item and block names MUST use Mineflayer's un-namespaced registry names such as dirt, oak_log, cobblestone, crafting_table.
- NEVER write minecraft_dirt or minecraft:dirt. Use dirt. NEVER write minecraft_crafting_table or minecraft:crafting_table. Use crafting_table.
- If coordinates are unknown, waypoint must be null.
- Do not claim that an unknown structure, chest, portal, mob or resource exists.
- Survival and avoiding obvious hazards have priority over speed.
- If gameMode is Creative, do NOT set inventory collection targets for mined blocks.
- Never request "build a structure", house, tower, shelter, bridge or arbitrary construction: the current agent does not yet have general block-placement actions.
- Do not keep collecting a resource after the numeric target is already satisfied.
- Inventory counts in state are authoritative. If inventory already meets a target, choose a DIFFERENT objective.
- If a visible player appears in nearbyPlayers, you may choose an objective to approach/follow that player without providing a waypoint.
- Players cannot be looted. "Loot" is valid only for an observed chest or barrel. Never propose "loot the player".
- Recent actions and results are authoritative. Do not repeat an objective that is clearly stuck or already completed.

CURRENT AGENT CAPABILITIES:
- approach/follow a visible player from nearbyPlayers
- travel toward a trusted planner waypoint
- explore a short distance north/east/south/west when no waypoint is known
- mine one observed desired resource block in Survival
- collect nearby dropped items
- open/loot observed chests and barrels
- craft an item when a valid recipe is currently available
- place a carried crafting table
- wait briefly for new observations
No general building, combat strategy, farming, smelting workflow, portal construction, or arbitrary block placement is available yet.
`;

export const plannerSystemPrompt = `You are the high-level planner for a Minecraft Mineflayer agent.
A separate controller (JEV) chooses exactly one bounded action from actions generated by code.
Do not output key presses, mouse movements, JavaScript, commands, cheats, teleportation, or invented observations.

Return ONLY valid JSON with this exact shape:
{
  "objective": "short current objective",
  "targets": {"minecraft_item_name": minimum_count},
  "waypoint": {"x": 0, "y": 64, "z": 0} or null,
  "desiredBlocks": ["minecraft_block_name"],
  "notes": "short guidance"
}
${sharedRules}`;

export const planCandidatesSystemPrompt = `You generate THREE distinct candidate high-level plans for a Minecraft Mineflayer agent.
A separate TypeSafe/JEV decision model will compare the candidates and choose one.
Do not decide which candidate is best yourself.
Do not output key presses, mouse movements, JavaScript, commands, cheats, teleportation, or invented observations.

Return ONLY valid JSON with this exact shape:
{
  "plans": [
    {
      "id": "p0",
      "objective": "short current objective",
      "targets": {"minecraft_item_name": minimum_count},
      "waypoint": {"x": 0, "y": 64, "z": 0} or null,
      "desiredBlocks": ["minecraft_block_name"],
      "notes": "short guidance"
    },
    {
      "id": "p1",
      "objective": "different feasible objective",
      "targets": {},
      "waypoint": null,
      "desiredBlocks": [],
      "notes": "short guidance"
    },
    {
      "id": "p2",
      "objective": "third distinct feasible objective",
      "targets": {},
      "waypoint": null,
      "desiredBlocks": [],
      "notes": "short guidance"
    }
  ]
}

Candidate diversity requirements:
- Produce exactly 3 candidates.
- The three objectives must be materially different, not paraphrases.
- Prefer one progression/resource candidate when useful, one navigation/observation candidate when useful, and one prerequisite/safety/crafting candidate when useful.
- Every candidate must be executable NOW from the supplied state with the listed agent capabilities.
- A crafting objective MUST include the exact craftable target item in targets. Do not say "craft a tool" with targets {}.
- A mining/resource objective MUST name the exact observed resource in targets and/or desiredBlocks.
- If a category is not useful, replace it with another genuinely distinct feasible objective.
- Never include an already-satisfied numeric target merely to create variety.
${sharedRules}`;

async function chatJson(systemPrompt, state, overrides={}) {
  const model = overrides.model || config.ollama.model;
  const timeoutMs = Number(overrides.timeoutMs ?? config.ollama.timeoutMs);
  const think = overrides.think ?? config.ollama.think;
  const keepAlive = overrides.keepAlive ?? '5m';
  const temperature = Number(overrides.temperature ?? 0.15);

  const started = performance.now();
  const response = await fetch(config.ollama.url + '/api/chat', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({
      model,
      stream: false,
      format: 'json',
      think,
      keep_alive: keepAlive,
      messages: [
        {role: 'system', content: systemPrompt},
        {role: 'user', content: JSON.stringify(state)}
      ],
      options: {temperature}
    }),
    signal: AbortSignal.timeout(timeoutMs)
  });

  if (!response.ok) {
    throw new Error(`Ollama HTTP ${response.status}: ${await response.text()}`);
  }

  const data = await response.json();
  return {
    json: parseJson(data?.message?.content),
    data,
    latencyMs: performance.now() - started,
    model,
    think
  };
}

export async function runPlanner(state, overrides={}) {
  const result = await chatJson(plannerSystemPrompt, state, overrides);
  return {
    plan: normalizePlan(result.json),
    data: result.data,
    latencyMs: result.latencyMs,
    model: result.model,
    think: result.think
  };
}

export async function makePlan(state, overrides={}) {
  return (await runPlanner(state, overrides)).plan;
}

export async function runPlanCandidates(state, overrides={}) {
  const result = await chatJson(planCandidatesSystemPrompt, state, overrides);
  const rawPlans = Array.isArray(result.json?.plans) ? result.json.plans : [];
  if (!rawPlans.length) {
    throw new Error('Ollama returned no plan candidates.');
  }

  const normalized = rawPlans
    .slice(0, 3)
    .map((plan, index) => normalizePlan(plan, 'p' + index));

  while (normalized.length < 3) {
    normalized.push(normalizePlan({
      id: 'p' + normalized.length,
      objective: 'Observe safely and reveal more terrain.',
      targets: {},
      waypoint: null,
      desiredBlocks: [],
      notes: 'Fallback candidate because Ollama returned fewer than three plans.'
    }, 'p' + normalized.length));
  }

  return {
    plans: normalized,
    data: result.data,
    latencyMs: result.latencyMs,
    model: result.model,
    think: result.think
  };
}

export async function makePlanCandidates(state, overrides={}) {
  return (await runPlanCandidates(state, overrides)).plans;
}
