import { config } from './config.mjs';

export function parseJson(text) {
  const cleaned = String(text || '')
    .replace(/^\s*```(?:json)?/i, '')
    .replace(/```\s*$/, '')
    .trim();
  return JSON.parse(cleaned);
}

export function normalizePlan(plan) {
  return {
    objective: String(plan?.objective || 'Observe the world and make safe progress.'),
    targets: plan?.targets && typeof plan.targets === 'object' ? plan.targets : {},
    waypoint: plan?.waypoint && Number.isFinite(Number(plan.waypoint.x))
      ? {
          x: Number(plan.waypoint.x),
          y: Number(plan.waypoint.y),
          z: Number(plan.waypoint.z)
        }
      : null,
    desiredBlocks: Array.isArray(plan?.desiredBlocks)
      ? plan.desiredBlocks.map(String).slice(0, 12)
      : [],
    notes: String(plan?.notes || '')
  };
}

export const plannerSystemPrompt = `You are the high-level planner for a Minecraft Mineflayer agent.
A separate controller (JEV) chooses exactly one bounded action from actions generated by code.
Do not output key presses, mouse movements, JavaScript, commands, cheats, teleportation, or invented observations.

Return ONLY valid JSON with this exact shape:
{
  "objective": "short current objective",
  "targets": {"minecraft_item_name": minimum_count},
  "waypoint": {"x": 0, "y": 64, "z": 0} or null,
  "desiredBlocks": ["minecraft_block_name"],
  "notes": "short guidance"
}

Rules:
- Use only information present in the supplied state.
- Keep the objective achievable with the CURRENT agent capabilities listed below.
- Prefer small, immediate milestones.
- Item and block names should use Minecraft registry-style names such as oak_log, cobblestone, crafting_table.
- If coordinates are unknown, waypoint must be null.
- Do not claim that an unknown structure, chest, portal, mob or resource exists.
- Survival and avoiding obvious hazards have priority over speed.
- If gameMode is Creative, do NOT set inventory collection targets for mined blocks; breaking blocks in Creative does not provide ordinary Survival drops.
- Never request "build a structure", house, tower, shelter, bridge or arbitrary construction: the current agent does not yet have general block-placement actions.
- Do not keep collecting a resource after the numeric target is already satisfied.
- Inventory counts in state are authoritative. If inventory already meets a target, choose a DIFFERENT objective.
- If a visible player appears in nearbyPlayers, you may choose an objective to approach/follow that player without providing a waypoint.

CURRENT AGENT CAPABILITIES:
- approach/follow a visible player from nearbyPlayers
- travel toward a trusted planner waypoint
- explore a short distance north/east/south/west when no waypoint is known
- mine one observed desired resource block in Survival
- collect nearby dropped items
- open/loot observed chests and barrels
- craft an item when a valid recipe is currently available
- place a carried crafting table
- wait briefly for new observations
No general building, combat strategy, farming, smelting workflow, portal construction, or arbitrary block placement is available yet.`;

export async function runPlanner(state, overrides={}) {
  const model = overrides.model || config.ollama.model;
  const timeoutMs = Number(overrides.timeoutMs ?? config.ollama.timeoutMs);
  const think = overrides.think ?? config.ollama.think;
  const keepAlive = overrides.keepAlive ?? '5m';
  const temperature = Number(overrides.temperature ?? 0.15);

  const started = performance.now();
  const response = await fetch(config.ollama.url + '/api/chat', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({
      model,
      stream: false,
      format: 'json',
      think,
      keep_alive: keepAlive,
      messages: [
        {role: 'system', content: plannerSystemPrompt},
        {role: 'user', content: JSON.stringify(state)}
      ],
      options: {temperature}
    }),
    signal: AbortSignal.timeout(timeoutMs)
  });

  if (!response.ok) {
    throw new Error(`Ollama HTTP ${response.status}: ${await response.text()}`);
  }

  const data = await response.json();
  const latencyMs = performance.now() - started;
  const plan = normalizePlan(parseJson(data?.message?.content));

  return {plan, data, latencyMs, model, think};
}

export async function makePlan(state, overrides={}) {
  return (await runPlanner(state, overrides)).plan;
}
